/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNoticesRouteImport } from './routes/_authenticated/notices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComplaintsIndexRouteImport } from './routes/_authenticated/complaints.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedComplaintsNewRouteImport } from './routes/_authenticated/complaints.new'
import { Route as AuthenticatedComplaintsIdRouteImport } from './routes/_authenticated/complaints.$id'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminNoticesRouteImport } from './routes/_authenticated/admin.notices'
import { Route as AuthenticatedAdminComplaintsRouteImport } from './routes/_authenticated/admin.complaints'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNoticesRoute = AuthenticatedNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplaintsIndexRoute =
  AuthenticatedComplaintsIndexRouteImport.update({
    id: '/complaints/',
    path: '/complaints/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplaintsNewRoute =
  AuthenticatedComplaintsNewRouteImport.update({
    id: '/complaints/new',
    path: '/complaints/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplaintsIdRoute =
  AuthenticatedComplaintsIdRouteImport.update({
    id: '/complaints/$id',
    path: '/complaints/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNoticesRoute =
  AuthenticatedAdminNoticesRouteImport.update({
    id: '/admin/notices',
    path: '/admin/notices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminComplaintsRoute =
  AuthenticatedAdminComplaintsRouteImport.update({
    id: '/admin/complaints',
    path: '/admin/complaints',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notices': typeof AuthenticatedNoticesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/complaints/new': typeof AuthenticatedComplaintsNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/complaints/': typeof AuthenticatedComplaintsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notices': typeof AuthenticatedNoticesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/complaints/new': typeof AuthenticatedComplaintsNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/complaints': typeof AuthenticatedComplaintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notices': typeof AuthenticatedNoticesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/_authenticated/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/_authenticated/complaints/new': typeof AuthenticatedComplaintsNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/complaints/': typeof AuthenticatedComplaintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/notices'
    | '/profile'
    | '/admin/complaints'
    | '/admin/notices'
    | '/admin/settings'
    | '/complaints/$id'
    | '/complaints/new'
    | '/admin/'
    | '/complaints/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/notices'
    | '/profile'
    | '/admin/complaints'
    | '/admin/notices'
    | '/admin/settings'
    | '/complaints/$id'
    | '/complaints/new'
    | '/admin'
    | '/complaints'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/notices'
    | '/_authenticated/profile'
    | '/_authenticated/admin/complaints'
    | '/_authenticated/admin/notices'
    | '/_authenticated/admin/settings'
    | '/_authenticated/complaints/$id'
    | '/_authenticated/complaints/new'
    | '/_authenticated/admin/'
    | '/_authenticated/complaints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notices': {
      id: '/_authenticated/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AuthenticatedNoticesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complaints/': {
      id: '/_authenticated/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof AuthenticatedComplaintsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complaints/new': {
      id: '/_authenticated/complaints/new'
      path: '/complaints/new'
      fullPath: '/complaints/new'
      preLoaderRoute: typeof AuthenticatedComplaintsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complaints/$id': {
      id: '/_authenticated/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof AuthenticatedComplaintsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notices': {
      id: '/_authenticated/admin/notices'
      path: '/admin/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AuthenticatedAdminNoticesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/complaints': {
      id: '/_authenticated/admin/complaints'
      path: '/admin/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AuthenticatedAdminComplaintsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNoticesRoute: typeof AuthenticatedNoticesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminComplaintsRoute: typeof AuthenticatedAdminComplaintsRoute
  AuthenticatedAdminNoticesRoute: typeof AuthenticatedAdminNoticesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedComplaintsIdRoute: typeof AuthenticatedComplaintsIdRoute
  AuthenticatedComplaintsNewRoute: typeof AuthenticatedComplaintsNewRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedComplaintsIndexRoute: typeof AuthenticatedComplaintsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNoticesRoute: AuthenticatedNoticesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminComplaintsRoute: AuthenticatedAdminComplaintsRoute,
  AuthenticatedAdminNoticesRoute: AuthenticatedAdminNoticesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedComplaintsIdRoute: AuthenticatedComplaintsIdRoute,
  AuthenticatedComplaintsNewRoute: AuthenticatedComplaintsNewRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedComplaintsIndexRoute: AuthenticatedComplaintsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
